name: mserve
description: A small (micro) web server.
version: 0.2.3
author: Devon Carew <devoncarew@gmail.com>
homepage: https://github.com/devoncarew/mserve.dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  args: ^1.0.0
  cli_util: ^0.1.3
  http_parser: ^3.0.0
  http_server: ^0.9.0
  intl: ^0.15.6
  mime: ^0.9.6
  package_config: ^1.0.3
  path: ^1.5.0
  shelf: ^0.7.2
  shelf_static: ^0.2.0

dev_dependencies:
  test: ^1.0.0

executables:
  mserve: null
