name: mserve
description: A small (micro) web server.
version: 0.1.3
author: Devon Carew <devoncarew@gmail.com>
homepage: https://github.com/devoncarew/mserve.dart

environment:
  sdk: '>=2.0.0-dev.30 <2.0.0'

dependencies:
  args: ^1.0.0
  cli_util: ^0.1.3
  http_server: ^0.9.0

dev_dependencies:
  test: ^0.12.0

executables:
  mserve: null
