name: mserve
description: A small (micro) web server.
version: 0.1.1
author: Devon Carew <devoncarew@gmail.com>
homepage: https://github.com/devoncarew/mserve.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  args: ^0.13.0
  http_server: ^0.9.0

dev_dependencies:
  test: ^0.12.0

executables:
  mserve: null
